name: Secret Scan (gitleaks)

on:
  push:
  pull_request:

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # <-- important for PR scan mode

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2.2.0
        with:
          args: detect --no-git --redact --config=.gitleaks.toml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
