name: Secret Scan (gitleaks)

on:
  pull_request:
  push:

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # config file we added earlier
          config: .gitleaks.toml
          redact: true
